import type {
  AdminUser,
  AdminCustomer,
  AdminCollector,
  AdminPickup,
  AdminLocation,
  AdminTimeSlot,
  AdminPayment,
  AdminTransaction,
  AdminNotification,
  AdminStats,
} from "@/types/admin";

export const adminUser: AdminUser = {
  id: "ADM-0001",
  name: "Admin",
  email: "admin@scrapwala.demo",
  phone: "+91 XXXXX XXXXX",
  role: "Super Admin",
  avatar: "",
};

export const adminStats: AdminStats = {
  totalPickups: 245,
  pendingPickups: 38,
  completedPickups: 189,
  activeCollectors: 12,
  totalCustomers: 420,
  todayRevenue: 18500,
};

export const adminCustomers: AdminCustomer[] = [
  {
    id: "CUST-0001",
    name: "Arjun Mehta",
    phone: "+91 XXXXX XXXXX",
    email: "arjun.mehta@demo.com",
    totalPickups: 12,
    completedPickups: 11,
    cancelledPickups: 1,
    totalEarned: 4850,
    joinedDate: "2026-03-15",
    status: "active",
    address: "12 Park Street, Near Victoria Memorial",
    city: "Kolkata",
  },
  {
    id: "CUST-0002",
    name: "Priya Banerjee",
    phone: "+91 XXXXX XXXXX",
    email: "priya.b@demo.com",
    totalPickups: 8,
    completedPickups: 8,
    cancelledPickups: 0,
    totalEarned: 3200,
    joinedDate: "2026-04-02",
    status: "active",
    address: "45B Salt Lake Sector V",
    city: "Kolkata",
  },
  {
    id: "CUST-0003",
    name: "Rahul Sharma",
    phone: "+91 XXXXX XXXXX",
    email: "rahul.sharma@demo.com",
    totalPickups: 5,
    completedPickups: 4,
    cancelledPickups: 1,
    totalEarned: 2100,
    joinedDate: "2026-05-10",
    status: "active",
    address: "78 Rashbehari Avenue",
    city: "Kolkata",
  },
  {
    id: "CUST-0004",
    name: "Sneha Dasgupta",
    phone: "+91 XXXXX XXXXX",
    email: "sneha.d@demo.com",
    totalPickups: 15,
    completedPickups: 14,
    cancelledPickups: 1,
    totalEarned: 7500,
    joinedDate: "2026-02-20",
    status: "active",
    address: "23 New Town Action Area I",
    city: "Kolkata",
  },
  {
    id: "CUST-0005",
    name: "Vikram Sen",
    phone: "+91 XXXXX XXXXX",
    email: "vikram.sen@demo.com",
    totalPickups: 3,
    completedPickups: 2,
    cancelledPickups: 1,
    totalEarned: 900,
    joinedDate: "2026-06-18",
    status: "inactive",
    address: "56 Howrah Station Road",
    city: "Howrah",
  },
  {
    id: "CUST-0006",
    name: "Ananya Roy",
    phone: "+91 XXXXX XXXXX",
    email: "ananya.roy@demo.com",
    totalPickups: 9,
    completedPickups: 9,
    cancelledPickups: 0,
    totalEarned: 4100,
    joinedDate: "2026-03-28",
    status: "active",
    address: "89 Gariahat Road, Ballygunge",
    city: "Kolkata",
  },
  {
    id: "CUST-0007",
    name: "Sourav Mondal",
    phone: "+91 XXXXX XXXXX",
    email: "sourav.m@demo.com",
    totalPickups: 6,
    completedPickups: 5,
    cancelledPickups: 1,
    totalEarned: 1800,
    joinedDate: "2026-07-05",
    status: "active",
    address: "31 Durgapur City Centre",
    city: "Durgapur",
  },
  {
    id: "CUST-0008",
    name: "Mita Chatterjee",
    phone: "+91 XXXXX XXXXX",
    email: "mita.c@demo.com",
    totalPickups: 4,
    completedPickups: 3,
    cancelledPickups: 1,
    totalEarned: 1350,
    joinedDate: "2026-08-01",
    status: "inactive",
    address: "14 Shyambazar 5 Point Crossing",
    city: "Kolkata",
  },
];

export const adminCollectors: AdminCollector[] = [
  {
    id: "COL-0001",
    name: "Rajesh Kumar",
    phone: "+91 XXXXX XXXXX",
    email: "rajesh.k@scrapwala.demo",
    area: "Salt Lake",
    todayPickups: 4,
    completedToday: 2,
    totalCompleted: 156,
    status: "on_pickup",
    joinedDate: "2025-11-10",
    rating: 4.8,
  },
  {
    id: "COL-0002",
    name: "Amit Pal",
    phone: "+91 XXXXX XXXXX",
    email: "amit.pal@scrapwala.demo",
    area: "New Town",
    todayPickups: 3,
    completedToday: 3,
    totalCompleted: 210,
    status: "available",
    joinedDate: "2025-09-22",
    rating: 4.9,
  },
  {
    id: "COL-0003",
    name: "Subhash Ghosh",
    phone: "+91 XXXXX XXXXX",
    email: "subhash.g@scrapwala.demo",
    area: "Howrah",
    todayPickups: 2,
    completedToday: 1,
    totalCompleted: 98,
    status: "on_pickup",
    joinedDate: "2026-01-15",
    rating: 4.5,
  },
  {
    id: "COL-0004",
    name: "Dipak Naskar",
    phone: "+91 XXXXX XXXXX",
    email: "dipak.n@scrapwala.demo",
    area: "Durgapur",
    todayPickups: 0,
    completedToday: 0,
    totalCompleted: 67,
    status: "offline",
    joinedDate: "2026-03-08",
    rating: 4.2,
  },
  {
    id: "COL-0005",
    name: "Manoj Das",
    phone: "+91 XXXXX XXXXX",
    email: "manoj.d@scrapwala.demo",
    area: "Kolkata Central",
    todayPickups: 5,
    completedToday: 3,
    totalCompleted: 182,
    status: "available",
    joinedDate: "2025-12-01",
    rating: 4.7,
  },
  {
    id: "COL-0006",
    name: "Bikash Roy",
    phone: "+91 XXXXX XXXXX",
    email: "bikash.r@scrapwala.demo",
    area: "Salt Lake",
    todayPickups: 1,
    completedToday: 0,
    totalCompleted: 43,
    status: "available",
    joinedDate: "2026-05-20",
    rating: 4.0,
  },
];

export const adminPickups: AdminPickup[] = [
  {
    id: "PKP-0001",
    customerId: "CUST-0001",
    customerName: "Arjun Mehta",
    customerPhone: "+91 XXXXX XXXXX",
    address: "12 Park Street, Near Victoria Memorial",
    city: "Kolkata",
    date: "2026-09-01",
    time: "10:00 AM - 12:00 PM",
    collectorId: "COL-0001",
    collectorName: "Rajesh Kumar",
    categories: ["Paper", "Plastic"],
    estimatedQuantity: "15 kg",
    estimatedAmount: "₹750",
    finalAmount: 780,
    status: "completed",
    paymentStatus: "paid",
    paymentMethod: "upi",
  },
  {
    id: "PKP-0002",
    customerId: "CUST-0004",
    customerName: "Sneha Dasgupta",
    customerPhone: "+91 XXXXX XXXXX",
    address: "23 New Town Action Area I",
    city: "Kolkata",
    date: "2026-09-03",
    time: "08:00 AM - 10:00 AM",
    collectorId: "COL-0002",
    collectorName: "Amit Pal",
    categories: ["E-Waste"],
    estimatedQuantity: "5 unit",
    estimatedAmount: "₹2500",
    finalAmount: 2400,
    status: "completed",
    paymentStatus: "paid",
    paymentMethod: "cash",
  },
  {
    id: "PKP-0003",
    customerId: "CUST-0003",
    customerName: "Rahul Sharma",
    customerPhone: "+91 XXXXX XXXXX",
    address: "78 Rashbehari Avenue",
    city: "Kolkata",
    date: "2026-09-05",
    time: "02:00 PM - 04:00 PM",
    collectorId: "COL-0005",
    collectorName: "Manoj Das",
    categories: ["Metals"],
    estimatedQuantity: "20 kg",
    estimatedAmount: "₹1600",
    finalAmount: 1550,
    status: "completed",
    paymentStatus: "paid",
    paymentMethod: "bank_transfer",
  },
  {
    id: "PKP-0004",
    customerId: "CUST-0002",
    customerName: "Priya Banerjee",
    customerPhone: "+91 XXXXX XXXXX",
    address: "45B Salt Lake Sector V",
    city: "Kolkata",
    date: "2026-09-08",
    time: "10:00 AM - 12:00 PM",
    collectorId: "COL-0006",
    collectorName: "Bikash Roy",
    categories: ["Paper", "Plastic", "Appliances"],
    estimatedQuantity: "25 kg",
    estimatedAmount: "₹1200",
    status: "scheduled",
  },
  {
    id: "PKP-0005",
    customerId: "CUST-0006",
    customerName: "Ananya Roy",
    customerPhone: "+91 XXXXX XXXXX",
    address: "89 Gariahat Road, Ballygunge",
    city: "Kolkata",
    date: "2026-09-09",
    time: "12:00 PM - 02:00 PM",
    collectorId: "COL-0001",
    collectorName: "Rajesh Kumar",
    categories: ["Paper"],
    estimatedQuantity: "10 kg",
    estimatedAmount: "₹400",
    status: "assigned",
  },
  {
    id: "PKP-0006",
    customerId: "CUST-0007",
    customerName: "Sourav Mondal",
    customerPhone: "+91 XXXXX XXXXX",
    address: "31 Durgapur City Centre",
    city: "Durgapur",
    date: "2026-09-10",
    time: "04:00 PM - 06:00 PM",
    collectorId: "COL-0004",
    collectorName: "Dipak Naskar",
    categories: ["Vehicle Scrap"],
    estimatedQuantity: "1 unit",
    estimatedAmount: "₹8500",
    status: "accepted",
  },
  {
    id: "PKP-0007",
    customerId: "CUST-0005",
    customerName: "Vikram Sen",
    customerPhone: "+91 XXXXX XXXXX",
    address: "56 Howrah Station Road",
    city: "Howrah",
    date: "2026-09-11",
    time: "08:00 AM - 10:00 AM",
    collectorId: "COL-0003",
    collectorName: "Subhash Ghosh",
    categories: ["Plastic", "E-Waste"],
    estimatedQuantity: "8 kg",
    estimatedAmount: "₹900",
    status: "on_the_way",
  },
  {
    id: "PKP-0008",
    customerId: "CUST-0001",
    customerName: "Arjun Mehta",
    customerPhone: "+91 XXXXX XXXXX",
    address: "12 Park Street, Near Victoria Memorial",
    city: "Kolkata",
    date: "2026-09-12",
    time: "10:00 AM - 12:00 PM",
    collectorId: "COL-0005",
    collectorName: "Manoj Das",
    categories: ["Metals", "Appliances"],
    estimatedQuantity: "30 kg",
    estimatedAmount: "₹3200",
    status: "arrived",
  },
  {
    id: "PKP-0009",
    customerId: "CUST-0004",
    customerName: "Sneha Dasgupta",
    customerPhone: "+91 XXXXX XXXXX",
    address: "23 New Town Action Area I",
    city: "Kolkata",
    date: "2026-09-14",
    time: "12:00 PM - 02:00 PM",
    collectorId: "COL-0002",
    collectorName: "Amit Pal",
    categories: ["Paper"],
    estimatedQuantity: "12 kg",
    estimatedAmount: "₹480",
    status: "weighing",
  },
  {
    id: "PKP-0010",
    customerId: "CUST-0008",
    customerName: "Mita Chatterjee",
    customerPhone: "+91 XXXXX XXXXX",
    address: "14 Shyambazar 5 Point Crossing",
    city: "Kolkata",
    date: "2026-09-15",
    time: "02:00 PM - 04:00 PM",
    collectorId: "COL-0001",
    collectorName: "Rajesh Kumar",
    categories: ["Plastic"],
    estimatedQuantity: "7 kg",
    estimatedAmount: "₹350",
    finalAmount: 340,
    status: "payment_pending",
    paymentStatus: "pending",
  },
  {
    id: "PKP-0011",
    customerId: "CUST-0003",
    customerName: "Rahul Sharma",
    customerPhone: "+91 XXXXX XXXXX",
    address: "78 Rashbehari Avenue",
    city: "Kolkata",
    date: "2026-09-16",
    time: "08:00 AM - 10:00 AM",
    categories: ["E-Waste"],
    estimatedQuantity: "3 unit",
    estimatedAmount: "₹1500",
    status: "cancelled",
  },
  {
    id: "PKP-0012",
    customerId: "CUST-0006",
    customerName: "Ananya Roy",
    customerPhone: "+91 XXXXX XXXXX",
    address: "89 Gariahat Road, Ballygunge",
    city: "Kolkata",
    date: "2026-09-17",
    time: "04:00 PM - 06:00 PM",
    categories: ["Paper", "Plastic"],
    estimatedQuantity: "18 kg",
    estimatedAmount: "₹850",
    status: "scheduled",
  },
];

export const adminLocations: AdminLocation[] = [
  {
    id: "LOC-0001",
    name: "Kolkata",
    city: "Kolkata",
    state: "West Bengal",
    pinCodes: "700001, 700002, 700003, 700004, 700005",
    status: "active",
    collectorsAvailable: 5,
    updatedAt: "2026-09-01",
  },
  {
    id: "LOC-0002",
    name: "Howrah",
    city: "Howrah",
    state: "West Bengal",
    pinCodes: "711101, 711102, 711103, 711104",
    status: "active",
    collectorsAvailable: 3,
    updatedAt: "2026-09-02",
  },
  {
    id: "LOC-0003",
    name: "Salt Lake",
    city: "Kolkata",
    state: "West Bengal",
    pinCodes: "700064, 700065, 700091, 700092",
    status: "active",
    collectorsAvailable: 4,
    updatedAt: "2026-09-03",
  },
  {
    id: "LOC-0004",
    name: "New Town",
    city: "Kolkata",
    state: "West Bengal",
    pinCodes: "700156, 700157, 700158, 700159",
    status: "active",
    collectorsAvailable: 3,
    updatedAt: "2026-09-04",
  },
  {
    id: "LOC-0005",
    name: "Durgapur",
    city: "Durgapur",
    state: "West Bengal",
    pinCodes: "713201, 713202, 713203, 713204, 713205",
    status: "active",
    collectorsAvailable: 2,
    updatedAt: "2026-09-05",
  },
];

export const adminTimeSlots: AdminTimeSlot[] = [
  {
    id: "TS-0001",
    label: "08:00 AM - 10:00 AM",
    startTime: "08:00",
    endTime: "10:00",
    capacity: 20,
    booked: 14,
    status: "active",
  },
  {
    id: "TS-0002",
    label: "10:00 AM - 12:00 PM",
    startTime: "10:00",
    endTime: "12:00",
    capacity: 20,
    booked: 18,
    status: "active",
  },
  {
    id: "TS-0003",
    label: "12:00 PM - 02:00 PM",
    startTime: "12:00",
    endTime: "14:00",
    capacity: 20,
    booked: 9,
    status: "active",
  },
  {
    id: "TS-0004",
    label: "02:00 PM - 04:00 PM",
    startTime: "14:00",
    endTime: "16:00",
    capacity: 20,
    booked: 11,
    status: "active",
  },
  {
    id: "TS-0005",
    label: "04:00 PM - 06:00 PM",
    startTime: "16:00",
    endTime: "18:00",
    capacity: 20,
    booked: 6,
    status: "active",
  },
];

export const adminPayments: AdminPayment[] = [
  {
    id: "PAY-0001",
    pickupId: "PKP-0001",
    customerName: "Arjun Mehta",
    amount: 780,
    method: "upi",
    date: "2026-09-01",
    status: "paid",
  },
  {
    id: "PAY-0002",
    pickupId: "PKP-0002",
    customerName: "Sneha Dasgupta",
    amount: 2400,
    method: "cash",
    date: "2026-09-03",
    status: "paid",
  },
  {
    id: "PAY-0003",
    pickupId: "PKP-0003",
    customerName: "Rahul Sharma",
    amount: 1550,
    method: "bank_transfer",
    date: "2026-09-05",
    status: "paid",
  },
  {
    id: "PAY-0004",
    pickupId: "PKP-0004",
    customerName: "Priya Banerjee",
    amount: 1200,
    method: "upi",
    date: "2026-09-08",
    status: "pending",
  },
  {
    id: "PAY-0005",
    pickupId: "PKP-0007",
    customerName: "Vikram Sen",
    amount: 900,
    method: "upi",
    date: "2026-09-11",
    status: "failed",
  },
  {
    id: "PAY-0006",
    pickupId: "PKP-0008",
    customerName: "Arjun Mehta",
    amount: 3200,
    method: "bank_transfer",
    date: "2026-09-12",
    status: "pending",
  },
  {
    id: "PAY-0007",
    pickupId: "PKP-0010",
    customerName: "Mita Chatterjee",
    amount: 340,
    method: "cash",
    date: "2026-09-15",
    status: "pending",
  },
  {
    id: "PAY-0008",
    pickupId: "PKP-0003",
    customerName: "Rahul Sharma",
    amount: 50,
    method: "upi",
    date: "2026-09-06",
    status: "refunded",
  },
  {
    id: "PAY-0009",
    pickupId: "PKP-0009",
    customerName: "Sneha Dasgupta",
    amount: 480,
    method: "upi",
    date: "2026-09-14",
    status: "pending",
  },
  {
    id: "PAY-0010",
    pickupId: "PKP-0005",
    customerName: "Ananya Roy",
    amount: 400,
    method: "cash",
    date: "2026-09-17",
    status: "pending",
  },
];

export const adminTransactions: AdminTransaction[] = [
  {
    id: "TXN-0001",
    pickupId: "PKP-0001",
    customerName: "Arjun Mehta",
    collectorName: "Rajesh Kumar",
    amount: 780,
    type: "pickup_payment",
    method: "upi",
    status: "paid",
    date: "2026-09-01",
  },
  {
    id: "TXN-0002",
    pickupId: "PKP-0002",
    customerName: "Sneha Dasgupta",
    collectorName: "Amit Pal",
    amount: 2400,
    type: "pickup_payment",
    method: "cash",
    status: "paid",
    date: "2026-09-03",
  },
  {
    id: "TXN-0003",
    pickupId: "PKP-0003",
    customerName: "Rahul Sharma",
    collectorName: "Manoj Das",
    amount: 1550,
    type: "pickup_payment",
    method: "bank_transfer",
    status: "paid",
    date: "2026-09-05",
  },
  {
    id: "TXN-0004",
    pickupId: "PKP-0003",
    customerName: "Rahul Sharma",
    collectorName: "Manoj Das",
    amount: 50,
    type: "refund",
    method: "upi",
    status: "refunded",
    date: "2026-09-06",
  },
  {
    id: "TXN-0005",
    pickupId: "PKP-0004",
    customerName: "Priya Banerjee",
    collectorName: "Bikash Roy",
    amount: 1200,
    type: "pickup_payment",
    method: "upi",
    status: "pending",
    date: "2026-09-08",
  },
  {
    id: "TXN-0006",
    pickupId: "PKP-0007",
    customerName: "Vikram Sen",
    collectorName: "Subhash Ghosh",
    amount: 900,
    type: "pickup_payment",
    method: "upi",
    status: "failed",
    date: "2026-09-11",
  },
  {
    id: "TXN-0007",
    pickupId: "PKP-0008",
    customerName: "Arjun Mehta",
    collectorName: "Manoj Das",
    amount: 200,
    type: "adjustment",
    method: "bank_transfer",
    status: "paid",
    date: "2026-09-12",
  },
  {
    id: "TXN-0008",
    pickupId: "PKP-0010",
    customerName: "Mita Chatterjee",
    collectorName: "Rajesh Kumar",
    amount: 340,
    type: "pickup_payment",
    method: "cash",
    status: "pending",
    date: "2026-09-15",
  },
];

export const adminNotifications: AdminNotification[] = [
  {
    id: "NOTIF-0001",
    title: "New Pickup Scheduled",
    message: "Arjun Mehta scheduled a pickup for 12 Sep 2026 at Park Street.",
    time: "2026-09-10T09:30:00",
    read: true,
    type: "pickup",
  },
  {
    id: "NOTIF-0002",
    title: "Payment Received",
    message: "₹780 received from Arjun Mehta via UPI for pickup PKP-0001.",
    time: "2026-09-01T14:20:00",
    read: true,
    type: "payment",
  },
  {
    id: "NOTIF-0003",
    title: "Collector Assigned",
    message: "Rajesh Kumar has been assigned to pickup PKP-0005.",
    time: "2026-09-09T07:45:00",
    read: false,
    type: "collector",
  },
  {
    id: "NOTIF-0004",
    title: "Payment Failed",
    message: "Payment of ₹900 failed for pickup PKP-0007. Customer: Vikram Sen.",
    time: "2026-09-11T11:15:00",
    read: false,
    type: "payment",
  },
  {
    id: "NOTIF-0005",
    title: "System Update",
    message: "Rate list updated for Paper and Plastic categories effective 01 Sep 2026.",
    time: "2026-09-01T06:00:00",
    read: true,
    type: "system",
  },
  {
    id: "NOTIF-0006",
    title: "Pickup Cancelled",
    message: "Rahul Sharma cancelled pickup PKP-0011 for E-Waste collection.",
    time: "2026-09-16T08:30:00",
    read: false,
    type: "pickup",
  },
  {
    id: "NOTIF-0007",
    title: "New Collector Registered",
    message: "Bikash Roy joined as a collector in Salt Lake area.",
    time: "2026-05-20T10:00:00",
    read: true,
    type: "collector",
  },
  {
    id: "NOTIF-0008",
    title: "Refund Processed",
    message: "₹50 refund processed for Rahul Sharma for pickup PKP-0003.",
    time: "2026-09-06T16:40:00",
    read: true,
    type: "payment",
  },
  {
    id: "NOTIF-0009",
    title: "High Demand Alert",
    message: "New Town area has 15 pending pickup requests. Consider assigning more collectors.",
    time: "2026-09-14T09:00:00",
    read: false,
    type: "system",
  },
  {
    id: "NOTIF-0010",
    title: "Collector Offline",
    message: "Dipak Naskar has gone offline in Durgapur area since 08:00 AM.",
    time: "2026-09-17T08:15:00",
    read: false,
    type: "collector",
  },
];

export const dashboardActivity = {
  scheduled: 12,
  assigned: 8,
  accepted: 5,
  onTheWay: 3,
  completed: 15,
  cancelled: 2,
};
